export const [
  menueOpener,
  bodyCover,
  menueCloser,
  navbar,
  count,
  incrementor,
  decrementor,
  toCart,
  itemsCount,
] = [
  "menue-opener",
  "body-cover",
  "menue-closer",
  "nav-bar",
  "count",
  "incrementor",
  "decrementor",
  "to-cart",
  "items-count",
].map(document.getElementById.bind(document));
